site_name: Alppi Documentation



nav:
  - Home: index.md
  - APIs: 
    - api/index.md
    - Authentication:
      - api/authentication/index.md 
      - Routes:
        - Login: api/authentication/login.md
        - Reset Password: api/authentication/reset_password.md

    - System:
      - api/system/index.md
      - Routes:
        - Campus: api/system/campus.md
        - Campus Settings: api/system/campus_settings.md
        - City: api/system/city.md
        - Class: api/system/class.md
        - Employee: api/system/employee.md
        - Pedagogical: api/system/pedagogical.md
        - Profile: api/system/profile.md
        - School Year: api/system/school_year.md
        - School Grade: api/system/school_grade.md
        - School Level: api/system/school_level.md
        - Shift: api/system/shift.md
        - Skill Grade: api/system/skill_grade.md
        - Skill Settings: api/system/skill_settings.md
        - Student: api/system/student.md
        - Student Presence: api/system/student_presence.md
        - Subject: api/system/subject.md
        - Subject Area: api/system/subject_area.md
        - Subject Grade: api/system/subject_grade.md
        - Term: api/system/term.md
        - Term type: api/system/term_type.md
        - User Group: api/system/user_group.md

    - Col√©gio Tiradentes:
      - api/ct_requests/index.md
      - Routes:
        - Internal Note: api/ct_requests/internal_note.md
        - Internal Note Comment: api/ct_requests/internal_note_comment.md
        - Internal Note Settings: api/ct_requests/internal_note_settings.md
        - Disciplinary Grade: api/ct_requests/disciplinary_grade.md
        - Regulaments: api/ct_requests/regulaments.md
        - Flow Disciplinary Grade: api/ct_requests/flow_disciplinary_grade.md
    
  - Release Notes:
    - Releases: # COLOCAR SEMPRE DECRESCENTE
      - System:
        - Version 1.0.0:
          - release-notes/system/v1/v1.0.12.md
          - release-notes/system/v1/v1.0.11.md
          - release-notes/system/v1/v1.0.10.md
          - release-notes/system/v1/v1.0.9.md
          - release-notes/system/v1/v1.0.8.md
          - release-notes/system/v1/v1.0.7.md
          - release-notes/system/v1/v1.0.6.md
          - release-notes/system/v1/v1.0.5.md
          - release-notes/system/v1/v1.0.4.md
          - release-notes/system/v1/v1.0.3.md
          - release-notes/system/v1/v1.0.2.md
          - release-notes/system/v1/v1.0.1.md
      - Authentication:
        - Version 1.0.0:
          - release-notes/authentication/v1/v1.0.2.md
          - release-notes/authentication/v1/v1.0.1.md
    
  - Permissions:
    - api/permissions/route_permissions.md
    - api/permissions/screen_permissions.md





theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  highlightjs: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.width.full
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.path
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/favicon.png


  icon:
    repo: fontawesome/brands/square-github
    admonition:
      note: octicons/pencil-16
      abstract: octicons/multi-select-16
      info: octicons/info-16
      tip: octicons/rocket-16
      success: octicons/check-circle-16
      question: octicons/question-16
      warning: octicons/stop-16
      failure: octicons/x-circle-16
      danger: octicons/alert-16
      bug: octicons/bug-16
      example: octicons/list-unordered-16
      quote: octicons/comment-16


plugins:
  - search
  - macros

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - css/crud.css
  - css/permissions.css

extra:
  status:
    new: Recently added
    deprecated: Deprecated
    tag: New tag
  
# Copyright
copyright: Copyright &copy; 2024 - 2025 Alppi Technology